//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// このソース コードは xsd によって自動生成されました。Version=4.8.3928.0 です。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.qlcplus.org/FixtureDefinition")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition", IsNullable=false)]
public partial class FixtureDefinition {
    
    private creatorType creatorField;
    
    private string manufacturerField;
    
    private string modelField;
    
    private typeType typeField;
    
    private channelType[] channelField;
    
    private modeType[] modeField;
    
    private physicalType physicalField;
    
    /// <remarks/>
    public creatorType Creator {
        get {
            return this.creatorField;
        }
        set {
            this.creatorField = value;
        }
    }
    
    /// <remarks/>
    public string Manufacturer {
        get {
            return this.manufacturerField;
        }
        set {
            this.manufacturerField = value;
        }
    }
    
    /// <remarks/>
    public string Model {
        get {
            return this.modelField;
        }
        set {
            this.modelField = value;
        }
    }
    
    /// <remarks/>
    public typeType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Channel")]
    public channelType[] Channel {
        get {
            return this.channelField;
        }
        set {
            this.channelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Mode")]
    public modeType[] Mode {
        get {
            return this.modeField;
        }
        set {
            this.modeField = value;
        }
    }
    
    /// <remarks/>
    public physicalType Physical {
        get {
            return this.physicalField;
        }
        set {
            this.physicalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public partial class creatorType {
    
    private string nameField;
    
    private string versionField;
    
    private string authorField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    public string Author {
        get {
            return this.authorField;
        }
        set {
            this.authorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public partial class modeChannelType {
    
    private string numberField;
    
    private string actsOnField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string Number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string ActsOn {
        get {
            return this.actsOnField;
        }
        set {
            this.actsOnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public partial class technicalType {
    
    private string powerConsumptionField;
    
    private connectorType dmxConnectorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string PowerConsumption {
        get {
            return this.powerConsumptionField;
        }
        set {
            this.powerConsumptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public connectorType DmxConnector {
        get {
            return this.dmxConnectorField;
        }
        set {
            this.dmxConnectorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public enum connectorType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3-pin")]
    Item3pin,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5-pin")]
    Item5pin,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3-pin and 5-pin")]
    Item3pinand5pin,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3-pin IP65")]
    Item3pinIP65,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5-pin IP65")]
    Item5pinIP65,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3.5 mm stereo jack")]
    Item35mmstereojack,
    
    /// <remarks/>
    Wireless,
    
    /// <remarks/>
    Other,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public partial class layoutType {
    
    private string widthField;
    
    private string heightField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string Width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string Height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public partial class focusType {
    
    private string typeField;
    
    private string panMaxField;
    
    private string tiltMaxField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string PanMax {
        get {
            return this.panMaxField;
        }
        set {
            this.panMaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string TiltMax {
        get {
            return this.tiltMaxField;
        }
        set {
            this.tiltMaxField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public partial class lensType {
    
    private string nameField;
    
    private decimal degreesMinField;
    
    private decimal degreesMaxField;
    
    private string prismFacesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal DegreesMin {
        get {
            return this.degreesMinField;
        }
        set {
            this.degreesMinField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal DegreesMax {
        get {
            return this.degreesMaxField;
        }
        set {
            this.degreesMaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string PrismFaces {
        get {
            return this.prismFacesField;
        }
        set {
            this.prismFacesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public partial class dimensionsType {
    
    private string widthField;
    
    private string heightField;
    
    private string depthField;
    
    private decimal weightField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string Width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string Height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string Depth {
        get {
            return this.depthField;
        }
        set {
            this.depthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public partial class bulbType {
    
    private string lumensField;
    
    private string typeField;
    
    private string colourTemperatureField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string Lumens {
        get {
            return this.lumensField;
        }
        set {
            this.lumensField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string ColourTemperature {
        get {
            return this.colourTemperatureField;
        }
        set {
            this.colourTemperatureField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public partial class physicalType {
    
    private bulbType bulbField;
    
    private dimensionsType dimensionsField;
    
    private lensType lensField;
    
    private focusType focusField;
    
    private layoutType layoutField;
    
    private technicalType technicalField;
    
    /// <remarks/>
    public bulbType Bulb {
        get {
            return this.bulbField;
        }
        set {
            this.bulbField = value;
        }
    }
    
    /// <remarks/>
    public dimensionsType Dimensions {
        get {
            return this.dimensionsField;
        }
        set {
            this.dimensionsField = value;
        }
    }
    
    /// <remarks/>
    public lensType Lens {
        get {
            return this.lensField;
        }
        set {
            this.lensField = value;
        }
    }
    
    /// <remarks/>
    public focusType Focus {
        get {
            return this.focusField;
        }
        set {
            this.focusField = value;
        }
    }
    
    /// <remarks/>
    public layoutType Layout {
        get {
            return this.layoutField;
        }
        set {
            this.layoutField = value;
        }
    }
    
    /// <remarks/>
    public technicalType Technical {
        get {
            return this.technicalField;
        }
        set {
            this.technicalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public partial class modeType {
    
    private physicalType physicalField;
    
    private modeChannelType[] channelField;
    
    private string[][] headField;
    
    private string nameField;
    
    /// <remarks/>
    public physicalType Physical {
        get {
            return this.physicalField;
        }
        set {
            this.physicalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Channel")]
    public modeChannelType[] Channel {
        get {
            return this.channelField;
        }
        set {
            this.channelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Channel", typeof(string), DataType="nonNegativeInteger", IsNullable=false)]
    public string[][] Head {
        get {
            return this.headField;
        }
        set {
            this.headField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public partial class aliasType {
    
    private string modeField;
    
    private string channelField;
    
    private string withField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Mode {
        get {
            return this.modeField;
        }
        set {
            this.modeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Channel {
        get {
            return this.channelField;
        }
        set {
            this.channelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string With {
        get {
            return this.withField;
        }
        set {
            this.withField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public partial class capabilityType {
    
    private aliasType[] aliasField;
    
    private string[] textField;
    
    private string minField;
    
    private string maxField;
    
    private capabilityPresetType presetField;
    
    private bool presetFieldSpecified;
    
    private string res1Field;
    
    private string res2Field;
    
    private string resField;
    
    private string colorField;
    
    private string color2Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Alias")]
    public aliasType[] Alias {
        get {
            return this.aliasField;
        }
        set {
            this.aliasField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string Min {
        get {
            return this.minField;
        }
        set {
            this.minField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string Max {
        get {
            return this.maxField;
        }
        set {
            this.maxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public capabilityPresetType Preset {
        get {
            return this.presetField;
        }
        set {
            this.presetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PresetSpecified {
        get {
            return this.presetFieldSpecified;
        }
        set {
            this.presetFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Res1 {
        get {
            return this.res1Field;
        }
        set {
            this.res1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Res2 {
        get {
            return this.res2Field;
        }
        set {
            this.res2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Res {
        get {
            return this.resField;
        }
        set {
            this.resField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Color2 {
        get {
            return this.color2Field;
        }
        set {
            this.color2Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public enum capabilityPresetType {
    
    /// <remarks/>
    SlowToFast,
    
    /// <remarks/>
    FastToSlow,
    
    /// <remarks/>
    NearToFar,
    
    /// <remarks/>
    FarToNear,
    
    /// <remarks/>
    BigToSmall,
    
    /// <remarks/>
    SmallToBig,
    
    /// <remarks/>
    ShutterOpen,
    
    /// <remarks/>
    ShutterClose,
    
    /// <remarks/>
    StrobeSlowToFast,
    
    /// <remarks/>
    StrobeFastToSlow,
    
    /// <remarks/>
    StrobeRandom,
    
    /// <remarks/>
    StrobeRandomSlowToFast,
    
    /// <remarks/>
    StrobeRandomFastToSlow,
    
    /// <remarks/>
    PulseSlowToFast,
    
    /// <remarks/>
    PulseFastToSlow,
    
    /// <remarks/>
    RampUpSlowToFast,
    
    /// <remarks/>
    RampUpFastToSlow,
    
    /// <remarks/>
    RampDownSlowToFast,
    
    /// <remarks/>
    RampDownFastToSlow,
    
    /// <remarks/>
    StrobeFrequency,
    
    /// <remarks/>
    StrobeFreqRange,
    
    /// <remarks/>
    PulseFrequency,
    
    /// <remarks/>
    PulseFreqRange,
    
    /// <remarks/>
    RampUpFrequency,
    
    /// <remarks/>
    RampUpFreqRange,
    
    /// <remarks/>
    RampDownFrequency,
    
    /// <remarks/>
    RampDownFreqRange,
    
    /// <remarks/>
    RotationStop,
    
    /// <remarks/>
    RotationIndexed,
    
    /// <remarks/>
    RotationClockwise,
    
    /// <remarks/>
    RotationClockwiseSlowToFast,
    
    /// <remarks/>
    RotationClockwiseFastToSlow,
    
    /// <remarks/>
    RotationCounterClockwise,
    
    /// <remarks/>
    RotationCounterClockwiseSlowToFast,
    
    /// <remarks/>
    RotationCounterClockwiseFastToSlow,
    
    /// <remarks/>
    ColorMacro,
    
    /// <remarks/>
    ColorDoubleMacro,
    
    /// <remarks/>
    ColorWheelIndex,
    
    /// <remarks/>
    GoboMacro,
    
    /// <remarks/>
    GoboShakeMacro,
    
    /// <remarks/>
    GenericPicture,
    
    /// <remarks/>
    PrismEffectOn,
    
    /// <remarks/>
    PrismEffectOff,
    
    /// <remarks/>
    LampOn,
    
    /// <remarks/>
    LampOff,
    
    /// <remarks/>
    ResetAll,
    
    /// <remarks/>
    ResetPanTilt,
    
    /// <remarks/>
    ResetPan,
    
    /// <remarks/>
    ResetTilt,
    
    /// <remarks/>
    ResetMotors,
    
    /// <remarks/>
    ResetGobo,
    
    /// <remarks/>
    ResetColor,
    
    /// <remarks/>
    ResetCMY,
    
    /// <remarks/>
    ResetCTO,
    
    /// <remarks/>
    ResetEffects,
    
    /// <remarks/>
    ResetPrism,
    
    /// <remarks/>
    ResetBlades,
    
    /// <remarks/>
    ResetIris,
    
    /// <remarks/>
    ResetFrost,
    
    /// <remarks/>
    ResetZoom,
    
    /// <remarks/>
    SilentModeOn,
    
    /// <remarks/>
    SilentModeOff,
    
    /// <remarks/>
    SilentModeAutomatic,
    
    /// <remarks/>
    Alias,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public partial class groupType {
    
    private string byteField;
    
    private groupEnumType valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string Byte {
        get {
            return this.byteField;
        }
        set {
            this.byteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public groupEnumType Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public enum groupEnumType {
    
    /// <remarks/>
    Intensity,
    
    /// <remarks/>
    Colour,
    
    /// <remarks/>
    Gobo,
    
    /// <remarks/>
    Prism,
    
    /// <remarks/>
    Shutter,
    
    /// <remarks/>
    Beam,
    
    /// <remarks/>
    Speed,
    
    /// <remarks/>
    Effect,
    
    /// <remarks/>
    Pan,
    
    /// <remarks/>
    Tilt,
    
    /// <remarks/>
    Maintenance,
    
    /// <remarks/>
    Nothing,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public partial class channelType {
    
    private groupType groupField;
    
    private colorType colourField;
    
    private bool colourFieldSpecified;
    
    private capabilityType[] capabilityField;
    
    private string nameField;
    
    private string defaultField;
    
    private channelPresetType presetField;
    
    private bool presetFieldSpecified;
    
    /// <remarks/>
    public groupType Group {
        get {
            return this.groupField;
        }
        set {
            this.groupField = value;
        }
    }
    
    /// <remarks/>
    public colorType Colour {
        get {
            return this.colourField;
        }
        set {
            this.colourField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ColourSpecified {
        get {
            return this.colourFieldSpecified;
        }
        set {
            this.colourFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Capability")]
    public capabilityType[] Capability {
        get {
            return this.capabilityField;
        }
        set {
            this.capabilityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string Default {
        get {
            return this.defaultField;
        }
        set {
            this.defaultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public channelPresetType Preset {
        get {
            return this.presetField;
        }
        set {
            this.presetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PresetSpecified {
        get {
            return this.presetFieldSpecified;
        }
        set {
            this.presetFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public enum colorType {
    
    /// <remarks/>
    Generic,
    
    /// <remarks/>
    Red,
    
    /// <remarks/>
    Green,
    
    /// <remarks/>
    Blue,
    
    /// <remarks/>
    Cyan,
    
    /// <remarks/>
    Magenta,
    
    /// <remarks/>
    Yellow,
    
    /// <remarks/>
    Amber,
    
    /// <remarks/>
    White,
    
    /// <remarks/>
    UV,
    
    /// <remarks/>
    Lime,
    
    /// <remarks/>
    Indigo,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public enum channelPresetType {
    
    /// <remarks/>
    IntensityMasterDimmer,
    
    /// <remarks/>
    IntensityMasterDimmerFine,
    
    /// <remarks/>
    IntensityDimmer,
    
    /// <remarks/>
    IntensityDimmerFine,
    
    /// <remarks/>
    IntensityRed,
    
    /// <remarks/>
    IntensityRedFine,
    
    /// <remarks/>
    IntensityGreen,
    
    /// <remarks/>
    IntensityGreenFine,
    
    /// <remarks/>
    IntensityBlue,
    
    /// <remarks/>
    IntensityBlueFine,
    
    /// <remarks/>
    IntensityCyan,
    
    /// <remarks/>
    IntensityCyanFine,
    
    /// <remarks/>
    IntensityMagenta,
    
    /// <remarks/>
    IntensityMagentaFine,
    
    /// <remarks/>
    IntensityYellow,
    
    /// <remarks/>
    IntensityYellowFine,
    
    /// <remarks/>
    IntensityAmber,
    
    /// <remarks/>
    IntensityAmberFine,
    
    /// <remarks/>
    IntensityWhite,
    
    /// <remarks/>
    IntensityWhiteFine,
    
    /// <remarks/>
    IntensityUV,
    
    /// <remarks/>
    IntensityUVFine,
    
    /// <remarks/>
    IntensityIndigo,
    
    /// <remarks/>
    IntensityIndigoFine,
    
    /// <remarks/>
    IntensityLime,
    
    /// <remarks/>
    IntensityLimeFine,
    
    /// <remarks/>
    IntensityHue,
    
    /// <remarks/>
    IntensityHueFine,
    
    /// <remarks/>
    IntensitySaturation,
    
    /// <remarks/>
    IntensitySaturationFine,
    
    /// <remarks/>
    IntensityLightness,
    
    /// <remarks/>
    IntensityLightnessFine,
    
    /// <remarks/>
    IntensityValue,
    
    /// <remarks/>
    IntensityValueFine,
    
    /// <remarks/>
    PositionPan,
    
    /// <remarks/>
    PositionPanFine,
    
    /// <remarks/>
    PositionTilt,
    
    /// <remarks/>
    PositionTiltFine,
    
    /// <remarks/>
    PositionXAxis,
    
    /// <remarks/>
    PositionYAxis,
    
    /// <remarks/>
    SpeedPanSlowFast,
    
    /// <remarks/>
    SpeedPanFastSlow,
    
    /// <remarks/>
    SpeedTiltSlowFast,
    
    /// <remarks/>
    SpeedTiltFastSlow,
    
    /// <remarks/>
    SpeedPanTiltSlowFast,
    
    /// <remarks/>
    SpeedPanTiltFastSlow,
    
    /// <remarks/>
    ColorMacro,
    
    /// <remarks/>
    ColorWheel,
    
    /// <remarks/>
    ColorWheelFine,
    
    /// <remarks/>
    ColorRGBMixer,
    
    /// <remarks/>
    ColorCTOMixer,
    
    /// <remarks/>
    ColorCTCMixer,
    
    /// <remarks/>
    ColorCTBMixer,
    
    /// <remarks/>
    GoboWheel,
    
    /// <remarks/>
    GoboWheelFine,
    
    /// <remarks/>
    GoboIndex,
    
    /// <remarks/>
    GoboIndexFine,
    
    /// <remarks/>
    ShutterStrobeSlowFast,
    
    /// <remarks/>
    ShutterStrobeFastSlow,
    
    /// <remarks/>
    ShutterIrisMinToMax,
    
    /// <remarks/>
    ShutterIrisMaxToMin,
    
    /// <remarks/>
    ShutterIrisFine,
    
    /// <remarks/>
    BeamFocusNearFar,
    
    /// <remarks/>
    BeamFocusFarNear,
    
    /// <remarks/>
    BeamFocusFine,
    
    /// <remarks/>
    BeamZoomSmallBig,
    
    /// <remarks/>
    BeamZoomBigSmall,
    
    /// <remarks/>
    BeamZoomFine,
    
    /// <remarks/>
    PrismRotationSlowFast,
    
    /// <remarks/>
    PrismRotationFastSlow,
    
    /// <remarks/>
    NoFunction,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public enum typeType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Color Changer")]
    ColorChanger,
    
    /// <remarks/>
    Dimmer,
    
    /// <remarks/>
    Effect,
    
    /// <remarks/>
    Fan,
    
    /// <remarks/>
    Flower,
    
    /// <remarks/>
    Hazer,
    
    /// <remarks/>
    Laser,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Moving Head")]
    MovingHead,
    
    /// <remarks/>
    Other,
    
    /// <remarks/>
    Scanner,
    
    /// <remarks/>
    Smoke,
    
    /// <remarks/>
    Strobe,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("LED Bar (Beams)")]
    LEDBarBeams,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("LED Bar (Pixels)")]
    LEDBarPixels,
}
