//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// このソース コードは xsd によって自動生成されました。Version=4.8.3928.0 です。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.qlcplus.org/FixtureDefinition")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition", IsNullable=false)]
public partial class FixtureDefinition {
    
    /// <remarks/>
    public creatorType Creator;
    
    /// <remarks/>
    public string Manufacturer;
    
    /// <remarks/>
    public string Model;
    
    /// <remarks/>
    public typeType Type;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Channel")]
    public channelType[] Channel;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Mode")]
    public modeType[] Mode;
    
    /// <remarks/>
    public physicalType Physical;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public partial class creatorType {
    
    /// <remarks/>
    public string Name;
    
    /// <remarks/>
    public string Version;
    
    /// <remarks/>
    public string Author;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public partial class modeChannelType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string Number;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string ActsOn;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public partial class technicalType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string PowerConsumption;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public connectorType DmxConnector;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public enum connectorType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3-pin")]
    Item3pin,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5-pin")]
    Item5pin,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3-pin and 5-pin")]
    Item3pinand5pin,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3-pin IP65")]
    Item3pinIP65,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5-pin IP65")]
    Item5pinIP65,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3.5 mm stereo jack")]
    Item35mmstereojack,
    
    /// <remarks/>
    Wireless,
    
    /// <remarks/>
    Other,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public partial class layoutType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string Width;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string Height;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public partial class focusType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Type;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string PanMax;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string TiltMax;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public partial class lensType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal DegreesMin;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal DegreesMax;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string PrismFaces;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public partial class dimensionsType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string Width;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string Height;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string Depth;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Weight;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public partial class bulbType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string Lumens;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Type;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string ColourTemperature;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public partial class physicalType {
    
    /// <remarks/>
    public bulbType Bulb;
    
    /// <remarks/>
    public dimensionsType Dimensions;
    
    /// <remarks/>
    public lensType Lens;
    
    /// <remarks/>
    public focusType Focus;
    
    /// <remarks/>
    public layoutType Layout;
    
    /// <remarks/>
    public technicalType Technical;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public partial class modeType {
    
    /// <remarks/>
    public physicalType Physical;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Channel")]
    public modeChannelType[] Channel;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Channel", typeof(string), DataType="nonNegativeInteger", IsNullable=false)]
    public string[] Head;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public partial class aliasType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Mode;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Channel;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string With;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public partial class capabilityType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Alias")]
    public aliasType[] Alias;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string Min;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string Max;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public capabilityPresetType Preset;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PresetSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Res1;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Res2;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Res;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Color;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Color2;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public enum capabilityPresetType {
    
    /// <remarks/>
    SlowToFast,
    
    /// <remarks/>
    FastToSlow,
    
    /// <remarks/>
    NearToFar,
    
    /// <remarks/>
    FarToNear,
    
    /// <remarks/>
    BigToSmall,
    
    /// <remarks/>
    SmallToBig,
    
    /// <remarks/>
    ShutterOpen,
    
    /// <remarks/>
    ShutterClose,
    
    /// <remarks/>
    StrobeSlowToFast,
    
    /// <remarks/>
    StrobeFastToSlow,
    
    /// <remarks/>
    StrobeRandom,
    
    /// <remarks/>
    StrobeRandomSlowToFast,
    
    /// <remarks/>
    StrobeRandomFastToSlow,
    
    /// <remarks/>
    PulseSlowToFast,
    
    /// <remarks/>
    PulseFastToSlow,
    
    /// <remarks/>
    RampUpSlowToFast,
    
    /// <remarks/>
    RampUpFastToSlow,
    
    /// <remarks/>
    RampDownSlowToFast,
    
    /// <remarks/>
    RampDownFastToSlow,
    
    /// <remarks/>
    StrobeFrequency,
    
    /// <remarks/>
    StrobeFreqRange,
    
    /// <remarks/>
    PulseFrequency,
    
    /// <remarks/>
    PulseFreqRange,
    
    /// <remarks/>
    RampUpFrequency,
    
    /// <remarks/>
    RampUpFreqRange,
    
    /// <remarks/>
    RampDownFrequency,
    
    /// <remarks/>
    RampDownFreqRange,
    
    /// <remarks/>
    RotationStop,
    
    /// <remarks/>
    RotationIndexed,
    
    /// <remarks/>
    RotationClockwise,
    
    /// <remarks/>
    RotationClockwiseSlowToFast,
    
    /// <remarks/>
    RotationClockwiseFastToSlow,
    
    /// <remarks/>
    RotationCounterClockwise,
    
    /// <remarks/>
    RotationCounterClockwiseSlowToFast,
    
    /// <remarks/>
    RotationCounterClockwiseFastToSlow,
    
    /// <remarks/>
    ColorMacro,
    
    /// <remarks/>
    ColorDoubleMacro,
    
    /// <remarks/>
    ColorWheelIndex,
    
    /// <remarks/>
    GoboMacro,
    
    /// <remarks/>
    GoboShakeMacro,
    
    /// <remarks/>
    GenericPicture,
    
    /// <remarks/>
    PrismEffectOn,
    
    /// <remarks/>
    PrismEffectOff,
    
    /// <remarks/>
    LampOn,
    
    /// <remarks/>
    LampOff,
    
    /// <remarks/>
    ResetAll,
    
    /// <remarks/>
    ResetPanTilt,
    
    /// <remarks/>
    ResetPan,
    
    /// <remarks/>
    ResetTilt,
    
    /// <remarks/>
    ResetMotors,
    
    /// <remarks/>
    ResetGobo,
    
    /// <remarks/>
    ResetColor,
    
    /// <remarks/>
    ResetCMY,
    
    /// <remarks/>
    ResetCTO,
    
    /// <remarks/>
    ResetEffects,
    
    /// <remarks/>
    ResetPrism,
    
    /// <remarks/>
    ResetBlades,
    
    /// <remarks/>
    ResetIris,
    
    /// <remarks/>
    ResetFrost,
    
    /// <remarks/>
    ResetZoom,
    
    /// <remarks/>
    SilentModeOn,
    
    /// <remarks/>
    SilentModeOff,
    
    /// <remarks/>
    SilentModeAutomatic,
    
    /// <remarks/>
    Alias,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public partial class groupType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string Byte;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public groupEnumType Value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public enum groupEnumType {
    
    /// <remarks/>
    Intensity,
    
    /// <remarks/>
    Colour,
    
    /// <remarks/>
    Gobo,
    
    /// <remarks/>
    Prism,
    
    /// <remarks/>
    Shutter,
    
    /// <remarks/>
    Beam,
    
    /// <remarks/>
    Speed,
    
    /// <remarks/>
    Effect,
    
    /// <remarks/>
    Pan,
    
    /// <remarks/>
    Tilt,
    
    /// <remarks/>
    Maintenance,
    
    /// <remarks/>
    Nothing,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public partial class channelType {
    
    /// <remarks/>
    public groupType Group;
    
    /// <remarks/>
    public colorType Colour;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ColourSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Capability")]
    public capabilityType[] Capability;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string Default;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public channelPresetType Preset;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PresetSpecified;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public enum colorType {
    
    /// <remarks/>
    Generic,
    
    /// <remarks/>
    Red,
    
    /// <remarks/>
    Green,
    
    /// <remarks/>
    Blue,
    
    /// <remarks/>
    Cyan,
    
    /// <remarks/>
    Magenta,
    
    /// <remarks/>
    Yellow,
    
    /// <remarks/>
    Amber,
    
    /// <remarks/>
    White,
    
    /// <remarks/>
    UV,
    
    /// <remarks/>
    Lime,
    
    /// <remarks/>
    Indigo,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public enum channelPresetType {
    
    /// <remarks/>
    IntensityMasterDimmer,
    
    /// <remarks/>
    IntensityMasterDimmerFine,
    
    /// <remarks/>
    IntensityDimmer,
    
    /// <remarks/>
    IntensityDimmerFine,
    
    /// <remarks/>
    IntensityRed,
    
    /// <remarks/>
    IntensityRedFine,
    
    /// <remarks/>
    IntensityGreen,
    
    /// <remarks/>
    IntensityGreenFine,
    
    /// <remarks/>
    IntensityBlue,
    
    /// <remarks/>
    IntensityBlueFine,
    
    /// <remarks/>
    IntensityCyan,
    
    /// <remarks/>
    IntensityCyanFine,
    
    /// <remarks/>
    IntensityMagenta,
    
    /// <remarks/>
    IntensityMagentaFine,
    
    /// <remarks/>
    IntensityYellow,
    
    /// <remarks/>
    IntensityYellowFine,
    
    /// <remarks/>
    IntensityAmber,
    
    /// <remarks/>
    IntensityAmberFine,
    
    /// <remarks/>
    IntensityWhite,
    
    /// <remarks/>
    IntensityWhiteFine,
    
    /// <remarks/>
    IntensityUV,
    
    /// <remarks/>
    IntensityUVFine,
    
    /// <remarks/>
    IntensityIndigo,
    
    /// <remarks/>
    IntensityIndigoFine,
    
    /// <remarks/>
    IntensityLime,
    
    /// <remarks/>
    IntensityLimeFine,
    
    /// <remarks/>
    IntensityHue,
    
    /// <remarks/>
    IntensityHueFine,
    
    /// <remarks/>
    IntensitySaturation,
    
    /// <remarks/>
    IntensitySaturationFine,
    
    /// <remarks/>
    IntensityLightness,
    
    /// <remarks/>
    IntensityLightnessFine,
    
    /// <remarks/>
    IntensityValue,
    
    /// <remarks/>
    IntensityValueFine,
    
    /// <remarks/>
    PositionPan,
    
    /// <remarks/>
    PositionPanFine,
    
    /// <remarks/>
    PositionTilt,
    
    /// <remarks/>
    PositionTiltFine,
    
    /// <remarks/>
    PositionXAxis,
    
    /// <remarks/>
    PositionYAxis,
    
    /// <remarks/>
    SpeedPanSlowFast,
    
    /// <remarks/>
    SpeedPanFastSlow,
    
    /// <remarks/>
    SpeedTiltSlowFast,
    
    /// <remarks/>
    SpeedTiltFastSlow,
    
    /// <remarks/>
    SpeedPanTiltSlowFast,
    
    /// <remarks/>
    SpeedPanTiltFastSlow,
    
    /// <remarks/>
    ColorMacro,
    
    /// <remarks/>
    ColorWheel,
    
    /// <remarks/>
    ColorWheelFine,
    
    /// <remarks/>
    ColorRGBMixer,
    
    /// <remarks/>
    ColorCTOMixer,
    
    /// <remarks/>
    ColorCTCMixer,
    
    /// <remarks/>
    ColorCTBMixer,
    
    /// <remarks/>
    GoboWheel,
    
    /// <remarks/>
    GoboWheelFine,
    
    /// <remarks/>
    GoboIndex,
    
    /// <remarks/>
    GoboIndexFine,
    
    /// <remarks/>
    ShutterStrobeSlowFast,
    
    /// <remarks/>
    ShutterStrobeFastSlow,
    
    /// <remarks/>
    ShutterIrisMinToMax,
    
    /// <remarks/>
    ShutterIrisMaxToMin,
    
    /// <remarks/>
    ShutterIrisFine,
    
    /// <remarks/>
    BeamFocusNearFar,
    
    /// <remarks/>
    BeamFocusFarNear,
    
    /// <remarks/>
    BeamFocusFine,
    
    /// <remarks/>
    BeamZoomSmallBig,
    
    /// <remarks/>
    BeamZoomBigSmall,
    
    /// <remarks/>
    BeamZoomFine,
    
    /// <remarks/>
    PrismRotationSlowFast,
    
    /// <remarks/>
    PrismRotationFastSlow,
    
    /// <remarks/>
    NoFunction,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qlcplus.org/FixtureDefinition")]
public enum typeType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Color Changer")]
    ColorChanger,
    
    /// <remarks/>
    Dimmer,
    
    /// <remarks/>
    Effect,
    
    /// <remarks/>
    Fan,
    
    /// <remarks/>
    Flower,
    
    /// <remarks/>
    Hazer,
    
    /// <remarks/>
    Laser,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Moving Head")]
    MovingHead,
    
    /// <remarks/>
    Other,
    
    /// <remarks/>
    Scanner,
    
    /// <remarks/>
    Smoke,
    
    /// <remarks/>
    Strobe,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("LED Bar (Beams)")]
    LEDBarBeams,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("LED Bar (Pixels)")]
    LEDBarPixels,
}
